import { useState, useEffect } from "react";

export default function Navbar({ onReset, hasPack, packData }) {
  const [theme, setTheme] = useState(() => {
    return localStorage.getItem("studymate_theme") || "dark";
  });

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
    localStorage.setItem("studymate_theme", theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme((prev) => (prev === "dark" ? "light" : "dark"));
  };

  const handleExport = () => {
    if (!packData) return;
    const content = `# Study Pack: ${packData.title || "Study Notes"}
Generated by StudyMate AI on ${new Date().toLocaleDateString()}

## Key Summary
${packData.summary.map((point) => `- ${point}`).join("\n")}

## Key Terms
${packData.keywords.join(", ")}

## Flashcards
${packData.cards.map((c, i) => `${i + 1}. Q: ${c.q}\n   A: ${c.a}`).join("\n\n")}

## Quiz Questions
${packData.quiz.map((q, i) => `${i + 1}. ${q.question}\n   Answer: ${q.answer}`).join("\n\n")}
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `studymate-pack-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <nav className="navbar">
      <div className="navbar-inner">
        <div className="brand" onClick={onReset}>
          <div className="brand-icon">📚</div>
          <div>
            <div className="brand-title">StudyMate AI</div>
          </div>
        </div>

        <div className="nav-actions">
          {hasPack && (
            <button className="btn btn-secondary" onClick={handleExport} title="Export study notes to Markdown">
              📥 Export Notes
            </button>
          )}

          {hasPack && (
            <button className="btn btn-ghost" onClick={onReset} title="New Upload">
              🔄 New Material
            </button>
          )}

          <button
            className="btn btn-secondary btn-icon-only"
            onClick={toggleTheme}
            title={`Switch to ${theme === "dark" ? "Light" : "Dark"} mode`}
          >
            {theme === "dark" ? "☀️" : "🌙"}
          </button>
        </div>
      </div>
    </nav>
  );
}
